[package]
name = "ucel-transport"
version = "0.1.0"
edition = "2021"

[dependencies]
ucel-core = { path = "../ucel-core" }
serde = { workspace = true }
tokio = { workspace = true, features = ["time", "sync"] }
bytes = { workspace = true }

rand = "0.8"
tokio-tungstenite = "0.24"

async-trait = "0.1"
futures-util = "0.3"
tracing = { workspace = true }
serde_json = { workspace = true }
base64 = "0.22"
ucel-journal = { path = "../ucel-journal" }
ucel-subscription-store = { path = "../ucel-subscription-store" }
ucel-ws-rules = { path = "../ucel-ws-rules" }