[package]
name = "ucel-cex-sbivc"
version = "0.1.0"
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
ucel-core = { path = "../ucel-core" }

[dev-dependencies]
