[package]
name = "ucel-testkit"
version = "0.1.0"
edition = "2021"

[dependencies]
ucel-core = { path = "../ucel-core" }
ucel-transport = { path = "../ucel-transport" }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
ucel-registry = { path = "../ucel-registry" }
ucel-cex-binance = { path = "../ucel-cex-binance" }
ucel-subscription-planner = { path = "../ucel-subscription-planner" }
